kind: PersistentVolume
apiVersion: v1
metadata:
  name: host-volume
  labels:
    service: seldon
spec:
  capacity:
    storage: 50Gi
  hostPath:
    path: /seldon-data
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
