kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  creationTimestamp: null
  labels:
    name: influxGrafana
    service: seldon
  name: influxdb-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      name: influxGrafana
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: influxGrafana
        service: seldon
    spec:
      containers:
      - image: seldonio/influxdb:1.0
        imagePullPolicy: IfNotPresent
        name: influxdb
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /seldon-data
          name: storage
      - env:
        - name: INFLUXDB_DATABASE
          value: seldon
        - name: INFLUXDB_SERVICE_URL
          value: http://localhost:8086
        - name: GF_SECURITY_ADMIN_USER
          value: admin
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: grafana-admin-password.txt
              name: grafana-admin-password
        - name: GRAFANA_PASSWD
          valueFrom:
            secretKeyRef:
              key: grafana-admin-password.txt
              name: grafana-admin-password
        - name: GF_AUTH_BASIC_ENABLED
          value: 'true'
        - name: GF_USERS_ALLOW_SIGN_UP
          value: 'false'
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: 'false'
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        image: seldonio/grafana:1.0
        imagePullPolicy: IfNotPresent
        name: grafana
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /seldon-data
          name: storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: seldon-claim
