apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kafka
    service: seldon
  name: kafka-service
spec:
  ports:
  - name: kafka-port
    port: 9092
    protocol: TCP
    targetPort: 9092
    nodePort: 30010
  selector:
    app: kafka
  sessionAffinity: None
  type: NodePort
