apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: monitoring-influxdb
  labels:
    service: seldon
spec:
  ports:
  - name: http
    port: 8083
    protocol: TCP
    targetPort: 8083
  - name: api
    port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    name: influxGrafana
  sessionAffinity: None
  type: ClusterIP
