apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: monitoring-grafana
  labels:
    service: seldon
spec:
  ports:
  - nodePort: 30002
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    name: influxGrafana
  sessionAffinity: None
  type: LoadBalancer
