apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    service: seldon
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
