apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: spark-ui-proxy
  labels:
    service: seldon
spec:
  ports:
  - nodePort: 30005
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    component: spark-ui-proxy
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
