kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: td-agent-server
  labels:
    component: td-agent-server
    service: seldon
spec:
  replicas: 1
  selector:
    matchLabels:
      name: td-agent-server
  template:
    metadata:
      name: td-agent-server
      labels:
        name: td-agent-server
        service: seldon
    spec:
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: seldon-claim
      containers:
      - name: td-agent-server
        image: seldonio/td-agent-server:1.0.5
        ports:
        - containerPort: 24224
          protocol: TCP
        volumeMounts:
        - name: data-volume
          mountPath: /seldon-data
