kind: Service
apiVersion: v1
metadata:
  name: zookeeper-3
  labels:
    name: zookeeper-3
    service: seldon
spec:
  ports:
  - name: client
    protocol: TCP
    port: 2181
    targetPort: 2181
  - name: followers
    protocol: TCP
    port: 2888
    targetPort: 2888
  - name: election
    protocol: TCP
    port: 3888
    targetPort: 3888
  selector:
    server-id: '3'
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
