kind: Service
apiVersion: v1
metadata:
  name: memcached2
  labels:
    app: memcache
    name: memcached2
    service: seldon
spec:
  ports:
  - protocol: TCP
    port: 11211
    targetPort: 11211
  selector:
    name: memcached2
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
