kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: memcached2
  labels:
    name: memcached2
    service: seldon
spec:
  replicas: 1
  selector:
    matchLabels:
      name: memcached2
  template:
    metadata:
      name: memcached2
      labels:
        name: memcached2
    spec:
      containers:
      - name: memcached2
        image: seldonio/memcached:0.1
        command:
        - memcached
        - -m
        - '512'
        resources:
          requests:
            memory: 260Mi
        ports:
        - containerPort: 11211
          protocol: TCP
