kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mysql
  labels:
    name: mysql
    service: seldon
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      name: mysql
      labels:
        name: mysql
        service: seldon
    spec:
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: seldon-claim
      containers:
      - name: mysql
        image: seldonio/mysql:1.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mypass
        resources:
          requests:
            memory: 3Gi
        volumeMounts:
        - name: data-volume
          mountPath: /seldon-data
