kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: redis
  labels:
    name: redis
    service: seldon
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
        service: seldon
      name: redis
    spec:
      containers:
      - image: redis
        name: redis-container
        ports:
        - containerPort: 6379
          protocol: TCP
