kind: Service
apiVersion: v1
metadata:
  name: td-agent-server
  creationTimestamp: null
  labels:
    name: td-agent-server
    service: seldon
spec:
  ports:
  - name: tcpport
    protocol: TCP
    port: 24224
    targetPort: 24224
  - name: udpport
    protocol: UDP
    port: 24224
    targetPort: 24224
  selector:
    name: td-agent-server
  type: ClusterIP
  sessionAffinity: None
