kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: zookeeper1
  labels:
    name: zookeeper1
    service: seldon
spec:
  replicas: 1
  selector:
    matchLabels:
      server-id: '1'
  template:
    metadata:
      name: zookeeper-1
      creationTimestamp: null
      labels:
        name: zookeeper1
        server-id: '1'
        service: seldon
    spec:
      containers:
      - name: server
        image: seldonio/zookeeper-k8s:1.0
        ports:
        - containerPort: 2181
          protocol: TCP
        - containerPort: 2888
          protocol: TCP
        - containerPort: 3888
          protocol: TCP
        env:
        - name: SERVER_ID
          value: '1'
        - name: MAX_SERVERS
          value: '3'
        resources: {}
        terminationMessagePath: /dev/termination-log
        imagePullPolicy: IfNotPresent
