apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: deep-mnist-webapp
  name: deep-mnist-webapp
  selfLink: /api/v1/namespaces//services/deep-mnist-webapp
spec:
  clusterIP: <unknown>
  ports:
  - nodePort: 30420
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: deep-mnist-webapp
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
