apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: deep-mnist-webapp
  name: deep-mnist-webapp
  selfLink: /apis/extensions/v1beta1/namespaces//deployments/deep-mnist-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      run: deep-mnist-webapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: deep-mnist-webapp
    spec:
      containers:
      - command:
        - /run_webapp.sh
        - 10.47.246.208
        - Y56HDQ2AR66M7CJ6KOCC
        - P073PQ6U8N0NAHT73GOL
        image: seldonio/deep_mnist_webapp:1.2
        imagePullPolicy: IfNotPresent
        name: deep-mnist-webapp
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
