kind: Job
apiVersion: batch/v1
metadata:
  name: load-model-tensorflow-deep-mnist
spec:
  template:
    metadata:
      name: load-model-tensorflow-deep-mnist
    spec:
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: seldon-claim
      containers:
      - name: load-model-tensorflow-deep-mnist
        image: seldonio/tensorflow_deep_mnist:2.2.5_v1
        command:
        - /home/seldon/load_model.sh
        - http://static.seldon.io/demos/tensorflow-deep-mnist/model_95.ckpt
        - /seldon-data/seldon-models/tensorflow_deep_mnist/1
        volumeMounts:
        - name: data-volume
          mountPath: /seldon-data
      restartPolicy: Never
