apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"name":"tensorflow-deep-mnist","service":"seldon","type":"microservice"},"name":"tensorflow-deep-mnist","namespace":"default"},"spec":{"ports":[{"port":5000,"protocol":"TCP","targetPort":5000}],"selector":{"name":"tensorflow-deep-mnist"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: null
  labels:
    name: tensorflow-deep-mnist
    service: seldon
    type: microservice
  name: tensorflow-deep-mnist
  selfLink: /api/v1/namespaces//services/tensorflow-deep-mnist
spec:
  clusterIP: <unknown>
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    name: tensorflow-deep-mnist
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
