apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"name":"tensorflow-deep-mnist","service":"seldon"},"name":"tensorflow-deep-mnist","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"name":"tensorflow-deep-mnist"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"name":"tensorflow-deep-mnist"},"name":"tensorflow-deep-mnist"},"spec":{"containers":[{"command":["python","/home/seldon/scripts/start_prediction_microservice.py","--model_name","tensorflow-deep-mnist","--pipeline","/seldon-data/seldon-models/tensorflow_deep_mnist/1/"],"image":"seldonio/pyseldon:2.2.5","imagePullPolicy":"IfNotPresent","name":"tensorflow-deep-mnist","ports":[{"containerPort":5000,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","volumeMounts":[{"mountPath":"/seldon-data","name":"data-volume"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"data-volume","persistentVolumeClaim":{"claimName":"seldon-claim"}}]}}},"status":{}}
  creationTimestamp: null
  generation: 1
  labels:
    name: tensorflow-deep-mnist
    service: seldon
  name: tensorflow-deep-mnist
  selfLink: /apis/extensions/v1beta1/namespaces//deployments/tensorflow-deep-mnist
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tensorflow-deep-mnist
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: tensorflow-deep-mnist
      name: tensorflow-deep-mnist
    spec:
      containers:
      - command:
        - python
        - /home/seldon/scripts/start_prediction_microservice.py
        - --model_name
        - tensorflow-deep-mnist
        - --pipeline
        - /seldon-data/seldon-models/tensorflow_deep_mnist/1/
        image: seldonio/pyseldon:2.2.5
        imagePullPolicy: IfNotPresent
        name: tensorflow-deep-mnist
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /seldon-data
          name: data-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: seldon-claim
status: {}
